spring:
  application:
    name: money-control
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true