spring:
  application:
    name: money-control
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
  mvc:
    problemdetails:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
